// Fixture builders for scheduler entities exercised through generic CRUD.
// Ids are auto-generated by the DB and surface as strings, so builders take the
// parent ids resolved at runtime by the test setup.

export function clientFor(businessId: string, userId: string) {
  return {
    business_id: businessId,
    user_id: userId,
    display_name: 'Homero Simpson',
    email: 'homero@dc.uba.ar',
    phone: '1144440000',
    notes: 'VIP',
  };
}

export function clientModifiedFor(businessId: string, userId: string) {
  return {
    business_id: businessId,
    user_id: userId,
    display_name: 'Homero J. Simpson',
    email: 'homero@dc.uba.ar',
    phone: '1155550000',
    notes: 'Regular',
  };
}

export function professionalFor(businessId: string) {
  return {
    business_id: businessId,
    user_id: null,
    display_name: 'Marge Bouvier',
    bio: 'Senior stylist',
  };
}

export function professionalModifiedFor(businessId: string) {
  return {
    business_id: businessId,
    user_id: null,
    display_name: 'Marge Simpson',
    bio: 'Lead stylist',
  };
}

export function serviceFor(businessId: string) {
  return {
    business_id: businessId,
    name: 'Haircut',
    description: 'Standard haircut',
    default_duration_minutes: 30,
    default_price_ars: '1500.00',
  };
}

export function serviceModifiedFor(businessId: string) {
  return {
    business_id: businessId,
    name: 'Haircut & Style',
    description: 'Cut and blow-dry',
    default_duration_minutes: 45,
    default_price_ars: '2500.00',
  };
}

export function clientPriceFor(clientId: string, professionalId: string, serviceId: string) {
  return {
    client_id: clientId,
    professional_id: professionalId,
    service_id: serviceId,
    price_ars: '1200.00',
  };
}
