-- Retired. The academic demo data (students/subjects/enrollments) was removed with the
-- scheduler cutover. Demo/foundation data is NOT seeded via SQL anymore — it lives in a
-- dev-only, idempotent runner outside the immutable migration history (D-22).
--
-- To load Phase 1 foundation demo data, run the seed runner instead:
--
--     npm run seed:foundation        # backend/src/seed-foundation.ts
--
-- It inserts one business, representative users, clients/professionals/resources, services,
-- optional per-client prices, and weekly schedules. It does NOT insert appointment, ledger,
-- or audit rows — those are seeded by their behavior phases.
